version: '3.7'

networks:
  com.othyn.network:
    name: com.othyn.network

services:
  com.othyn.app:
    container_name: com.othyn.app
    build:
        context: .
        dockerfile: dockerfile
    networks:
      - com.othyn.network
    ports:
      - 8888:80
    volumes:
      - ./dist:/usr/share/nginx/html
