version: '3.7'

networks:
  com.othyn.network:
    name: com.othyn.network

services:
  com.othyn.app:
    container_name: com.othyn.app
    build:
        context: .
        dockerfile: dockerfile
    networks:
      - com.othyn.network
    ports:
      - 3000:3000
    # volumes:
      # - .:/var/www
      # - /var/www/node_modules
      # anonymous persistent volume to stop node_modules within the container being overriden by local
      # - ./logs:/root/.npm/_logs
      # for debugging container issues
